tool/copyright: allow author from args, more error checking

diff --git a/deploy/tool/copyright b/deploy/tool/copyright
--- a/deploy/tool/copyright
+++ b/deploy/tool/copyright
@@ -2,28 +2,34 @@
 
 set -eu
 
-if [ "$#" != "1" ] || [ "$1" = "-h" ] ; then
+me=$(basename "$0")
+
+if [ "$#" -lt "1" ] || [ "$1" = "-h" ] ; then
   cat << EOF
-usage: $(basename "$0") [-h] FILE
+usage: $me [-h] FILE [AUTHOR=GIT]
 Prints copyright notice for FILE fetching author and date from git index.
+If AUTHOR is specified, uses AUTHOR and file change time.
 EOF
   exit 1
 fi
 
-
 file=$1
+author=${2:-GIT}
 
-list=$(git ls-files -- "$file" )
-if [ -z "$list" ] ; then
-  echo "File '$file' not found in index" 1>&2
-  exit 1
+if [ "$author" == "GIT" ] ; then
+  list=$(git ls-files -- "$file" )
+  if [ -z "$list" ] ; then
+    echo "$me: File '$file' not found in index" 1>&2
+    exit 1
+  fi
+  git=$(git log --date=format:'%d.%m.%Y' --reverse -- "$file" | head -n3)
+  author=$(echo "$git" | sed -En 's/.*Author: (.*?) <.*/\1/p')
+  date=$(echo "$git" | sed -En 's/.*Date:   (.*?)/\1/p')
+else
+  date=$(stat -c%Z "$file")
+  date=$(date -d "@$date" +%d.%m.%Y)
 fi
-
-
-git=`git log --date=format:'%d.%m.%Y' --reverse -- "$file" | head -n3`
-author=`echo "$git" | sed -En 's/.*Author: (.*?) <.*/\1/p'`
-date=`echo "$git" | sed -En 's/.*Date:   (.*?)/\1/p'`
-year=`echo "$date" | sed -En 's/[0-9]*\.[0-9]*\.([0-9]*)/\1/p'`
+year=$(echo "$date" | sed -En 's/[0-9]*\.[0-9]*\.([0-9]*)/\1/p')
 
 cat << EOF
 // Created by $author on $date
