tool/part: add openmp

diff --git a/deploy/tool/part b/deploy/tool/part
--- a/deploy/tool/part
+++ b/deploy/tool/part
@@ -2,7 +2,7 @@
 
 set -eu
 
-if [ "$#" != 7 ] ; then
+if [ "$#" != 7 ] && [ "$#" != 8 ]; then
   echo "usage: $0 nx ny nz bsx bsy bsz np
 Partition mesh.
 ARGS:
@@ -14,9 +14,16 @@ commands to set px,bx,bsx etc " >&2
   exit 1
 fi
 
-r="`ch.part0 $@`"
+IFS=' ' read nx ny nz bsx bsy bsz np omp <<< "$@"
+if [ "${omp:-1}" != 1 ] ; then
+  if (( $np % $omp != 0 )) ; then
+    echo "Abort, np=$np must be divisible by omp=$omp" >&2
+    exit 1
+  fi
+  np=$(($np / $omp))
+fi
 
-IFS=' ' read nx ny nz bsx bsy bsz np <<< "$@"
+r="`ch.part0 $nx $ny $nz $bsx $bsy $bsz $np`"
 IFS=' ' read px py pz bx by bz <<< "$r"
 
 echo "set int px $px
@@ -31,3 +38,7 @@ set int bsx $bsx
 set int bsy $bsy
 set int bsz $bsz
 "
+
+if [ "${omp:-1}" != 1 ] ; then
+  echo "set int openmp 1"
+fi
