poc/18_inside: testing on grid

diff --git a/poc/18_inside/example/grid b/poc/18_inside/example/grid
--- a/poc/18_inside/example/grid
+++ b/poc/18_inside/example/grid
@@ -11,70 +11,65 @@ $me -r ratio -p degree > vtk
 exit 2
 }
 
-Rflag=0 Pflag=0
+Iflag=0
 while test $# -ne 0
 do case "$1" in
        -h) usg ;;
-       -r) shift
-           if test $# -eq 0; then err '-r needs an argument'; fi
-           r=$1; shift; Rflag=1 ;;
-       -p) shift
-           if test $# -eq 0; then err '-p needs an argument'; fi
-           p=$1; shift; Pflag=1 ;;
+       -i) shift
+           if test $# -eq 0; then err '-i needs an argument'; fi
+           i=$1; shift; Iflag=1 ;;
        *) err "unknown argument '$1'" ;;
    esac
 done
 
-if test $Rflag -eq 0; then err '-r is not set'; fi
-if test $Pflag -eq 0; then err '-p is not set'; fi
+if test $Iflag -eq 0; then err '-i is not set'; fi
 
 tmp=/tmp/grid.$$
 trap 'rm -f $tmp; exit 2' 1 2 3 14 15
 
-awk -v r="$r" -v p="$p" -v tmp=$tmp '
+awk -v Input="$i" -v tmp=$tmp '
 BEGIN {
-    ox = -0.5
-    oy = 0
-    sx = 0.005
-    sy = 0.005
-    nx = 200
+    lx = ly = lz = 2
+    ox = -lx/2
+    oy = -ly/2
+    oz = -lz/2
+    nx = 100
     ny = 100
-    cmd = "./main -r %.16g -p %.16g > " tmp
-    cmd = sprintf(cmd, r, p)
-    for (j = 0; j < ny; j++)
-        for (i = 0; i < nx; i++) {
-            x = ox + sx * i
-            y = oy + sy * j
-            print x, y | cmd
+    nz = 100
+    sx = lx/nx
+    sy = ly/ny
+    sz = lz/nz
+    cmd = "./point2 %s > " tmp
+    cmd = sprintf(cmd, Input)
+    for (k = 0; k < nz; k++)
+        for (j = 0; j < ny; j++)
+    	    for (i = 0; i < nx; i++) {
+		x = ox + sx * i
+		y = oy + sy * j
+		z = oz + sz * k
+		print x, y, z | cmd
         }
     close(cmd)
     i = 0
-    while ((getline < tmp) == 1) {
-        vx[i] = $1
-        vy[i] = $2
-        pressure[i] = $3
-        psi[i] = $4
-        i++
+    while ((getline < tmp) == 1)
+        data[i++] = $1
+    if (i != nx * ny * nz) {
+	printf "grid: assert failed" | "cat >&2"
+	exit(2)
     }
+	
     print "# vtk DataFile Version 2.0"
-    print "generated by hydro"
+    print "generated by aphros"
     print "ASCII"
     print "DATASET STRUCTURED_POINTS"
-    printf "DIMENSIONS %d %d 1\n", nx, ny
-    printf "ORIGIN %.16g %.16g 0\n", ox, oy
-    printf "SPACING %.16g %.16g 0\n", sx, sy
-    printf "POINT_DATA %d\n", nx * ny
-    print "VECTORS v double"
-    for (i = 0; i < nx * ny; i++)
-        print vx[i], vy[i], 0
-    print "SCALARS psi double"
+    printf "DIMENSIONS %d %d %d\n", nx, ny, nz
+    printf "ORIGIN %.16g %.16g %.16g\n", ox, oy, oz
+    printf "SPACING %.16g %.16g %.16g\n", sx, sy, sz
+    printf "POINT_DATA %d\n", nx * ny * nz
+    print "SCALARS data int"
     print "LOOKUP_TABLE default"
-    for (i = 0; i < nx * ny; i++)
-        print psi[i]
-    print "SCALARS pressure double"
-    print "LOOKUP_TABLE default"
-    for (i = 0; i < nx * ny; i++)
-        print pressure[i]
+    for (i = 0; i < nx * ny * nz; i++)
+        print data[i]
 }
 '
 
